name: jos_exp
# experiment parameters
num_trials: 60
num_epochs: 15
batch_size: 128
num_worlds: 16
max_cells: 4
# how many data-points per verb/truth-value pair
items_per_bin: 16000
# how many times to try rejection sampling
tries_per_bin: 60000
test_bin_size: 4000
# how often to eval
eval_steps: 50
stop_loss: 0.02
# verbs
verbs:
  - Know
  - BeCertain
  - Knopinion
  - Wondows
# model parameters
num_classes: 2
input_feature: "x"
layers: 
  - units: 128
    activation: elu
    dropout: 0.1
  - units: 128
    activation: elu
    dropout: 0.1
  - units: 128
    activation: elu
    dropout: 0.1
  - units: 128
    activation: elu
    dropout: 0.1